apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotesmicroservice-deployment
  labels:
    app: PASQuotesMicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PASQuotesMicroservice	  
  template:
    metadata:
      labels:
        app: PASQuotesMicroservice
    spec:
      containers:
      - name: pasquotesmicroservice
        image: policyadministrationsystem.azurecr.io/pasquotesmicroservice:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: policyadminsecret
---
apiVersion: v1
kind: Service
metadata:
  name: quotesmicroserviepasservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: PASQuotesMicroservice