apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotesmicroservice-deployment
  labels:
    app: QuotesMicroservicePAS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: QuotesMicroservicePAS	  
  template:
    metadata:
      labels:
        app: QuotesMicroservicePAS
    spec:
      containers:
      - name: quotesmicroserviepas
        image: authmicroservicecr.azurecr.io/quotesmicroservice:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: authsecret
---
apiVersion: v1
kind: Service
metadata:
  name: quotesmicroserviepasservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: QuotesMicroservicePAS